### ISSUE TITLE
Module did not self-register.

### ISSUE THREAD

**Issue by samu** [atom/highlights#19]
I use highlights in [my package](https://github.com/samu/git-diff-details) and am getting this error during startup:

`Failed to load package named 'git-diff-details' Error: Module did not self-register.`

I do `Highlights = require 'highlights'` in my code, if i remove that line the package loads fine.

**Comment by kevinsawicki** [comment]
What version of highlights are you using and on what version of Atom?

**Comment by samu** [comment]
I linked `git-diff-deatils` into the packages folder via `apm link` and am using the most recent version of highlights, `1.2.0`. Atom is at `0.179.0`

**Comment by kevinsawicki** [comment]
Try running `apm rebuild` at the root of `git-diff-details`

**Comment by samu** [comment]
Yep, that worked! Thanks a lot for the fast reply.
