### ISSUE TITLE
How to set background and font size

### ISSUE THREAD

**Issue by samu** [atom/highlights#20]
This isn't a bug but a question, i hope you don't mind me posting it here.

I'm using highlights in [this package](https://github.com/samu/git-diff-details). Until recently i used this hacky [line](https://github.com/samu/git-diff-details/blob/master/lib/git-diff-details-view.coffee#L71) to make the diffs appear with the same code highlighting and background as the editor views, however this doesn't work any longer in recent atom versions. If i remove that line (meaning that i use the raw output highlights delivers), i get a white background and different font size, code highlighting seems to be the same though. Any suggestions how i could make those inline diffs appear in same size and background color again?

**Comment by kevinsawicki** [comment]
You might want to check out how the markdown-preview uses the `atom-text-editor` custom element to render code blocks using the default styles.

https://github.com/atom/markdown-preview/blob/2bcbadac3980f1aeb455f7078bd1fdfb4e6fe6b1/lib/renderer.coffee#L101

You can then style it like so: https://github.com/atom/markdown-preview/blob/2bcbadac3980f1aeb455f7078bd1fdfb4e6fe6b1/styles/markdown-preview.less#L140
