### ISSUE TITLE
Use Highlights in an Electron app: "Uncaught Error: Module version mismatch

### ISSUE THREAD

**Issue by maveonair** [atom/highlights#22]
I want to use highlights in an app that I am building with [Electron](http://electron.atom.io/) but I always get the error message when I start the app:

```
"Uncaught Error: Module version mismatch. Expected 44, got 14.", source: ATOM_SHELL_ASAR.js (137)
```
I have added highlights as a dependencies via npm: ```npm install highlights --save``` and I start the app via a gulp task and npm:

```js
// using ES6 with Babel
import Highlights from 'highlights';

// More code...
```

```js
// More tasks above...
gulp.task('run', ['clean-and-build'], function() {
  return run('electron .').exec();
});
```

```sh
$ npm start # which executes gulp run
```

What would be the proper way to add highlights as an dependencies to an Electron based app?

**Comment by maxbrunsfeld** [comment]
Hi @maveonair,

That error means that the native code in `highlights` was compiled using the headers from a different version of node than Electron uses. In this case, it was compiled to work with the version of node that you have installed on your system. You need to rebuild `highlights` to work with electron.

The best explanation of this is [this page](http://electron.atom.io/docs/v0.28.0/tutorial/using-native-node-modules/) from the electron docs.

Let me know if you have further problems; we'll make sure you get this working.

**Comment by paperscissors** [comment]
Wondering, is there a way to get an output of what module is actually causes these Module version mismatches?

I'm actually not getting them when I run npm start, but when I run npm run release. npm start runs my application just fine.
